version: "3.3"
services:
  postgres:
    container_name: betterbanking_postgres
    image: postgres
    environment:
      POSTGRES_USER: betterbankingadm
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: better_banking
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/scripts.d:/docker-entrypoint-initdb.d